# Generated by Django 3.1.7 on 2021-05-13 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Allocated',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('hositalType', models.CharField(choices=[('GOVT', 'Government'), ('PRIV', 'Private')], max_length=10)),
                ('hdu', models.IntegerField()),
                ('oxygenated', models.IntegerField()),
                ('ventilators', models.IntegerField()),
                ('icu', models.IntegerField()),
                ('normal', models.IntegerField()),
                ('total', models.IntegerField()),
                ('ahdu', models.IntegerField()),
                ('aoxygenated', models.IntegerField()),
                ('aventilators', models.IntegerField()),
                ('aicu', models.IntegerField()),
                ('anormal', models.IntegerField()),
                ('atotal', models.IntegerField()),
            ],
        ),
    ]
